INSERT INTO person VALUES (12,'Lars','kageVej 48','CBS','Marketing','64738946','Larsg@mail.com','Lars@hotmail.com','75847293','En produktiv gut','1984-08-13',47368);
INSERT INTO person VALUES (13,'Peter','nordlundevej 98','CBS','Marketing','19472849','Peter@mail.com','Lars@hotmail.com','75847293','En produktiv gut','1984-08-13',56700);
INSERT INTO person VALUES (14,'Morten','charllotenborg 48','CBS','Marketing','48736402','Marketing@mail.com','Lars@hotmail.com','75847293','En produktiv gut','1984-08-13',43789);
INSERT INTO person VALUES (15,'Lilian','Parken 100','CBS','Marketing','37483917','Lilian@mail.com','Lars@hotmail.com','75847293','En produktiv gut','1984-08-13',59832);
INSERT INTO person VALUES (16,'Mark','borresvej 12','Engineer','Marketing','27489375','Mark@mail.com','Lars@hotmail.com','75847293','En produktiv gut','1984-08-13',36748);
INSERT INTO person VALUES (17,'Karsten','Lyngby midt 15','CBS','Marketing','27584930','Karsten@mail.com','Lars@hotmail.com','75847293','En produktiv gut','1984-08-13',45673);
INSERT INTO person VALUES (18,'Per','centrumPark 32','CBS','Marketing','56473829','Per@mail.com','Lars@hotmail.com','75847293','En produktiv gut','1984-08-13',41283);
INSERT INTO person VALUES (19,'Mathias','Landevejen 48','CBS','Marketing','10928374','Mathiasg@mail.com','Lars@hotmail.com','75847293','En produktiv gut','1984-08-13',39847);
INSERT INTO person VALUES (20,'Peder','nakskovvej 48','CBS','Marketing','37281964','Peder@mail.com','Lars@hotmail.com','75847293','En produktiv gut','1984-08-13',43000);
INSERT INTO person VALUES (21,'Mogens','bredvej 24','Engineer','Marketing','54839203','Mogens@mail.com','Mogens@hotmail.com','78674639','God arbejdsgang','1976-09-37',67000);

INSERT INTO partner VALUES (2,'Morten','Morten1234','PARTNER');
INSERT INTO partner VALUES (3,'Nikolaj','Nikolaj1234','PARTNER');
INSERT INTO partner VALUES (4,'Shaher','Shaher1234','PARTNER');
INSERT INTO partner VALUES (5,'Salman','Salman1234','PARTNER');
INSERT INTO partner VALUES (6,'Censor','Censor1234','PARTNER');
INSERT INTO partner VALUES (7,'Ronni','Dalsgaard','PARTNER');
INSERT INTO partner VALUES (8,'Inge-Lise','Salomon','PARTNER');
INSERT INTO partner VALUES (9,'Finn','Gustafsson','PARTNER');
INSERT INTO partner VALUES (10,'Niels','Grenaa','PARTNER');

INSERT INTO researcher VALUES (2,'Jeppe','Jeppe4321','RESEARCHER');
INSERT INTO researcher VALUES (3,'Morten','Morten4321','RESEARCHER');
INSERT INTO researcher VALUES (4,'Nikolaj','Nikolaj4321','RESEARCHER');
INSERT INTO researcher VALUES (5,'Shaher','Shaher4321','RESEARCHER');
INSERT INTO researcher VALUES (6,'Salman','Salman4321','RESEARCHER');
INSERT INTO researcher VALUES (7,'Censor','Censor4321','RESEARCHER');
INSERT INTO researcher VALUES (8,'Mark','Gilde','RESEARCHER');
INSERT INTO researcher VALUES (9,'Jannik','Sandbjerg','RESEARCHER');
INSERT INTO researcher VALUES (10,'Rasmus','Bjerg','RESEARCHER');
INSERT INTO researcher VALUES (11,'Anders','Matthesen','RESEARCHER');
INSERT INTO researcher VALUES (12,'Birgitte','Jensen','RESEARCHER');
INSERT INTO researcher VALUES (13,'Barrack','Obama','RESEARCHER');
INSERT INTO researcher VALUES (14,'Amin','Jensen','RESEARCHER');
INSERT INTO researcher VALUES (15,'Elias','Ehlers','RESEARCHER');
INSERT INTO researcher VALUES (16,'Dan','Andersen','RESEARCHER');
INSERT INTO researcher VALUES (17,'Mogens','Glistrup','RESEARCHER');
INSERT INTO researcher VALUES (18,'Uldus','Jensen','RESEARCHER');
INSERT INTO researcher VALUES (19,'James','Bubber','RESEARCHER');
INSERT INTO researcher VALUES (20,'Chili','Claus','RESEARCHER');

INSERT INTO branch VALUES ('IT','TELE');
INSERT INTO branch VALUES ('Bager','Konditor');
INSERT INTO branch VALUES ('Mekaniker','Hydraulik');
INSERT INTO branch VALUES ('HÃ¥ndvÃ¦rker','TÃ¸mrer');
INSERT INTO branch VALUES ('Elektro','Signal');
INSERT INTO branch VALUES ('Sundhed','Hjemmepleje');
INSERT INTO branch VALUES ('Marketing','Stof');
INSERT INTO branch VALUES ('Salg','Detail');
INSERT INTO branch VALUES ('Konsulent','IT');
INSERT INTO branch VALUES ('IT','Kommunikation');
INSERT INTO branch VALUES ('IT','Medier');
INSERT INTO branch VALUES ('IT','Trådløs');
INSERT INTO branch VALUES ('IT','Hospitaler');
INSERT INTO branch VALUES ('Stålprodukter','Støbning');
INSERT INTO branch VALUES ('Alkohol','Destillation');
INSERT INTO branch VALUES ('Handel','IT');

INSERT INTO company VALUES ('Maskinen','Mekaniker','MekanikerStrÃ¦de 107','64738291','Lars svensknÃ¸gle', 'Peter pedal'); 
INSERT INTO company VALUES ('PC World','IT','ITStrÃ¦de 48','738492839','peter Larsen', 'Morten motherboard'); 
INSERT INTO company VALUES ('Samsung','IT','ITvej 314','64738291','Birger gløgg', 'Peter pedal'); 
INSERT INTO company VALUES ('Apple','Salg','æblevej 189','67483964','kalle bunde', 'Pippi Langstrømpe'); 
INSERT INTO company VALUES ('HP','Handel','bubbivej','62392864','Henrik Petersen', 'Helena Patricksen'); 
INSERT INTO company VALUES ('Google','Elektro','klodsvej','98674563','Mannie Klistersen', 'Jens bredballe'); 


INSERT INTO cases VALUES ('Maskin Sagen', 'Maskinen',2);
INSERT INTO cases VALUES ('PCWORLD', 'PC World',3);
INSERT INTO cases VALUES ('SAMSUNG', 'Samsung',4);
INSERT INTO cases VALUES ('APPLE1', 'Apple',5);
INSERT INTO cases VALUES ('APPLE2', 'Apple',6);
INSERT INTO cases VALUES ('HP', 'HP',7);
INSERT INTO cases VALUES ('GOOGLE1', 'Google',8);
INSERT INTO cases VALUES ('GOOGLE2', 'Goggle',9);
INSERT INTO cases VALUES ('GOOGLE3', 'Goggle',10);

INSERT INTO researcheroncase VALUES (2,'Maskin Sagen');
INSERT INTO researcheroncase VALUES (3,'Maskin Sagen');
INSERT INTO researcheroncase VALUES (4,'PCWORLD');
INSERT INTO researcheroncase VALUES (5,'PCWORLD');
INSERT INTO researcheroncase VALUES (6,'PCWORLD');
INSERT INTO researcheroncase VALUES (7,'SAMSUNG');
INSERT INTO researcheroncase VALUES (8,'APPLE1');
INSERT INTO researcheroncase VALUES (9,'APPLE2');
INSERT INTO researcheroncase VALUES (10,'HP');
INSERT INTO researcheroncase VALUES (11,'HP');
INSERT INTO researcheroncase VALUES (12,'GOOGLE1');
INSERT INTO researcheroncase VALUES (13,'GOOGLE1');
INSERT INTO researcheroncase VALUES (14,'GOGLE2');
INSERT INTO researcheroncase VALUES (15,'GOOGLE3');
INSERT INTO researcheroncase VALUES (16,'GOOGLE3');
INSERT INTO researcheroncase VALUES (17,'SAMSUNG');
INSERT INTO researcheroncase VALUES (18,'Maskin Sagen');
INSERT INTO researcheroncase VALUES (19,'SAMSUNG');
INSERT INTO researcheroncase VALUES (20,'HP');
INSERT INTO researcheroncase VALUES (2,'HP');
INSERT INTO researcheroncase VALUES (3,'PCWORLD');
INSERT INTO researcheroncase VALUES (4,'SAMSUNG');
INSERT INTO researcheroncase VALUES (5,'GOOGLE2');
INSERT INTO researcheroncase VALUES (6,'HP');
INSERT INTO researcheroncase VALUES (7,'APPLE1');
INSERT INTO researcheroncase VALUES (8,'SAMSUNG');
INSERT INTO researcheroncase VALUES (9,'Maskin Sagen');
INSERT INTO researcheroncase VALUES (10,'PCWORLD');
INSERT INTO researcheroncase VALUES (11,'GOOGLE3');
INSERT INTO researcheroncase VALUES (12,'HP');
INSERT INTO researcheroncase VALUES (13,'Maskin Sagen');
INSERT INTO researcheroncase VALUES (14,'APPLE1');
INSERT INTO researcheroncase VALUES (15,'GOOGLE1');
INSERT INTO researcheroncase VALUES (16,'HP');
INSERT INTO researcheroncase VALUES (17,'Maskin Sagen');
INSERT INTO researcheroncase VALUES (18,'APPLE2');
INSERT INTO researcheroncase VALUES (19,'GOOGLE1');
INSERT INTO researcheroncase VALUES (20,'SAMSUNG');
INSERT INTO researcheroncase VALUES (2,'SAMSUNG');
INSERT INTO researcheroncase VALUES (3,'SAMSUNG');
INSERT INTO researcheroncase VALUES (4,'GOOGLE1');
INSERT INTO researcheroncase VALUES (5,'HP');
INSERT INTO researcheroncase VALUES (6,'APPLE2');
INSERT INTO researcheroncase VALUES (7,'HP');
INSERT INTO researcheroncase VALUES (8,'GOOGLE2');
INSERT INTO researcheroncase VALUES (9,'SAMSUNG');
INSERT INTO researcheroncase VALUES (10,'Maskin Sagen');
INSERT INTO researcheroncase VALUES (11,'APPLE2');
INSERT INTO researcheroncase VALUES (12,'SAMSUNG');
INSERT INTO researcheroncase VALUES (13,'HP');
INSERT INTO researcheroncase VALUES (14,'SAMSUNG');
INSERT INTO researcheroncase VALUES (15,'Maskin Sagen');
INSERT INTO researcheroncase VALUES (16,'APPLE1');
INSERT INTO researcheroncase VALUES (17,'APPLE2');
INSERT INTO researcheroncase VALUES (18,'GOOGLE3');
INSERT INTO researcheroncase VALUES (19,'APPLE2');
INSERT INTO researcheroncase VALUES (20,'GOOGLE3');
